services:
  postgres:
    image: postgres:latest
    container_name: logistics-node-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_logistics_backend_data:/var/lib/postgresql/data
    networks:
      - logistics-node-network

volumes:
  postgres_logistics_backend_data:

networks:
  logistics-node-network:
    external: true
